apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-cicd
  labels:
    app: backend-cicd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-cicd
  template:
    metadata:
      labels:
        app: backend-cicd
    spec:
      containers:
      - name: backend
        image: ghcr.io/elitikka/lemp-app2/backend:main # Aiemmin oli: backend:latest
        imagePullPolicy: Always # Aiemmin oli: Never  # Käytä paikallista imagea Minikubessa
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: backend-config-cicd
              key: DB_HOST
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: backend-config-cicd
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: backend-config-cicd
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: MYSQL_PASSWORD
---
apiVersion: v1
kind: Service
metadata:
  name: backend-cicd
spec:
  selector:
    app: backend-cicd
  ports:
  - port: 5000
    targetPort: 5000
  type: ClusterIP