apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-cicd
  labels:
    app: frontend-cicd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-cicd
  template:
    metadata:
      labels:
        app: frontend-cicd
    spec:
      containers:
      - name: nginx
        image: ghcr.io/elitikka/lemp-app2/frontend:latest
        imagePullPolicy: Always # Aiemmin oli: Never  # Käytä paikallista imagea Minikubessa
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-cicd
spec:
  selector:
    app: frontend-cicd
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30385 # Muutettu 30384 --> 30385 # Lisätty, kun vaihdettu type LoadBalancerista NodePorttiin
  type: NodePort # LoadBalancer  # Minikubessa käytetään NodePort:ia

  # Note to self: 
  # Oli duplikaattina esim. frontend-service.yaml missä oli samat service tiedot. Ne nyt on tässä samassa. 
  # Poistin erilliset -service.yaml tiedostot.